services:
- type: web
  name: turborepo-remote-cache
  region: singapore
  plan: Free
  env: docker
  disk:
    name: disk-turborepo-remote-cache
    mountPath: /tmp/turborepo_remote_cache
    sizeGB: 10
  envVars:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: 3000
    - key: TURBO_TOKEN
      generateValue: true
    - key: LOG_LEVEL
      value: info
    - key: STORAGE_PROVIDER
      value: local
    - key: STORAGE_PATH
      value: /turborepo_remote_cache
    # - key: AWS_ACCESS_KEY_ID
    #   value: 
    # - key: AWS_SECRET_ACCESS_KEY
    #   value: 
    # - key: AWS_REGION
    #   value: 
    # - key: S3_ENDPOINT
    #   value: 